### ISSUE TITLE
첫번째 이슈

### ISSUE THREAD

**Issue by hyunjeng** [hyunjeng/test#1]
여러분이 작성한 코드에 버그가 있거나, 기능을 개선할 때에 사용하면 됩니다.

--------------------------
#### 사용자 로그인 정보 개선
현재 시스템은 사용자가 로그인 했을 때, 로그인 시간 정보를 기록하고 있지 않습니다.

**Comment by hyunjeng** [comment]
https://github.com/hyunjeng/test/blob/01ab76ccb2d812c60a404dfe3d59ae1c20b8a24b/main.cpp#L7

이 부분이 잘못되어 있음

**Comment by dbwodnjs902** [comment]
....

**Comment by hyunjeng** [comment]
이 이슈는 기능 개발과 상관없으므로 닫도록 하겠습니다.
